### ISSUE TITLE
(Suggestion) Auto Equip

### ISSUE THREAD

**Issue by Zypre** [daemitus/ZodiacBuddy#1]
I have no idea if this is possible, but I assume so;

It would be nice if the addon checks whether the correct weapon is equipped when you click to teleport, then auto equip it if not.
(P.S. Thank you for the Yes Already addon as well. These two combined speeds up my farming sooo much)

**Comment by daemitus** [comment]
Automatically equipping things wouldn't happen. A text warning might be
doable though.
