### ISSUE TITLE
Sylph Bonnet - (slightly) wrong location 

### ISSUE THREAD

**Issue by Maxxymillion** [daemitus/ZodiacBuddy#10]
Sent to wrong location: Sylph Bonnet - was sent to East Shroud X24 Y17, actual location is East Shroud X26 Y13. 
was for Book of Skyfall Two, not sure that matters though

**Comment by ZachieBlade** [comment]
Can confirm. I had the same issue and came to report the same thing.

https://gyazo.com/dcdb986202e81effe3d7b1fb57e2d7dc
