### ISSUE TITLE
Novus light bonus overflow issue

### ISSUE THREAD

**Issue by fiskero94** [daemitus/ZodiacBuddy#21]
I am currently doing Novus light farming and discovered an issue.

I had been farming Tam-Tara Deepcroft with bonus light from 12:00 to 14:00. At around 13:58 i start a last run, to see if I would still get bonus light even if the clock goes past 14:00. Once I complete the run at round 14:01, I found out that I still got the bonus light. 

The issue is that now the plugin reports that 14:00 to 16:00 is also a bonus light period for the Tam-Tara Deepcroft, but I did another run of the dungeon (around 14:05 ish) and confirmed that I don't get bonus light in that dungeon anymore.

I believe this is the solution: 
When reporting the light bonus, the plugin needs to attribute the light bonus to the dungeon start time, instead of the dungeon completion time.

Other:
This issue occured on EU, Light, Phoenix at 2022-08-14 between 11:50 - 12:20 (UTC)
My character name is Jade Tea

**Comment by Hiroa** [comment]
Yeah, I was aware of this. The bonus of light is determined when you start the duty. So a duty started before the reset will be count has bonus duty if you end it after the reset.

The server side know the previous detected duty and ignore report with a duty detected on the last period but there is nothing on the client side.
I will check on the server later that it's working properly with the information that you provided.

For the client side it would be better to ask the server before notifying the user.
Not very fond of it, I would like the plugin to still work without the server but I will think of something.
That need also a change on the server side to notify when a report is ignored.

**Comment by daemitus** [comment]
fix pending
