### ISSUE TITLE
Integration with Sonar

### ISSUE THREAD

**Issue by mishugashu** [daemitus/ZodiacBuddy#3]
Feature request (inquiry?):

Would it be possible to integrate with the Sonar plugin, so that it automatically tracks the FATEs that you need? That would be fantastic!

Thanks for the plugin, btw, it is fantastic.

**Comment by daemitus** [comment]
They have no integration or commands to be able to toggle it, however if you go into the Sonar config, you can add all the fates
(names are here https://github.com/daemitus/ZodiacBuddy/blob/master/ZodiacBuddy/Stages/Atma/Data/BraveBook.cs#L324) and set them to show for your entire datacenter. 

I basically did all 9 books in two days. Its trivial when you dont have to wait for the fates.
