### ISSUE TITLE
Feature Request: Light Bonus Tracker

### ISSUE THREAD

**Issue by chernobog** [daemitus/ZodiacBuddy#4]
I'd love to see a tracker (like in Sonar) for duties that are granting bonus light, or be able to set notifications when duties start granting light above a set value.

**Comment by daemitus** [comment]
afaik no way of checking if bonus light is active, without running a
dungeon and checking.

**Comment by chernobog** [comment]
That's what I figured. You'd have to make it do some automated crowdsourcing.
