### ISSUE TITLE
[Bug] Dungeon Selector

### ISSUE THREAD

**Issue by spiral6** [daemitus/ZodiacBuddy#5]
Selecting the dungeons does not consistently open and select in the Duty Finder.

Tested:
Book of Skyfire I (Yoshimitsu Atma - NIN)
- Selecting Galvanth the Dominator - The Tam-Tara Deepcroft -- FAIL
- Selecting Isgebind - The Stone Vigil -- FAIL
- Selecting Diabolos - The Lost City of Amdapor -- PASS

Selecting Diabolos actually does work and do what was expected. The others do not.

**Comment by spiral6** [comment]
Similarly:

Book of Skyfire II (Yoshimitsu Atma - NIN)
- Selecting Aiatar - Brayflox's Longstop - FAIL
- Selecting Ouranos - Copperbell Mines [Hard] - PASS
- Selecting tonberry king - The Wanderer's Palace - PASS

**Comment by daemitus** [comment]
The recent dungeon rework changed some numbers. fixed.
